# 开发环境启用Swagger
swagger:
  enable: true
wx:
  url:
    redirect_uri: http://yyx.frps.happyqing.com/api/auth/token
  public_number:
    app_id: wx0c8866109c2c76ab
    app_secret: de53761d03472d56bd4e57cd4b9f13c7
    config_token: developer_home